In [2]:
import matplotlib.path as mpath
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
boundary=np.array([[0,0],[0,5],[4,5],[4,3],[6,3],[6,0],[0,0]])
x_min, x_max=0,8
y_min, y_max=0,8
x,y=np.meshgrid(np.arange(x_min,x_max),np.arange(y_min,y_max))
grid_points=np.vstack((x.ravel(),y.ravel())).T
bpath=mpath.Path(boundary)


In [13]:
x=6
y=5

matrix=np.zeros((y,x))
for i in range(y):
    for j in range(x):
        if bpath.contains_point((j+0.5,i+0.5)):
            matrix[i][j]=1 
for i in matrix[::-1]:
    print(i)
#print(matrix)
bwidth=len(matrix[0])
bheight=len(matrix)
print(bheight, bwidth)
placement=[]




print(placement)

[1. 1. 1. 1. 0. 0.]
[1. 1. 1. 1. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
5 6
[]


In [19]:
def find_rectangles(matrix):
    rows, cols = len(matrix), len(matrix[0])
    rectangles = []
    rectanglesdim=[]
    for r in range(rows):
        for c in range(cols):
            if matrix[r][c] == 1:
                max_width = cols - c  # Max possible width
                
                for w in range(max_width):
                    if matrix[r][c + w] == 0:  # Stop width expansion
                        break
                    
                    max_height = rows - r  # Max possible height
                    
                    for h in range(max_height):
                        if any(matrix[r + h][c + i] == 0 for i in range(w + 1)):  
                            break  # Stop height expansion
                        
                        # Found a valid rectangle
                        
                        rectanglesdim.append([r,c,h,w,h*w])
                        rectangles.append(((r, c), (r + h, c + w)))

    return rectangles, rectanglesdim

rects, rectdim=find_rectangles(matrix)

for i in range(len(rects)):
    print(f"Bottom-left: {rects[i][0]}, Top-right: {rects[i][1]}")
    print(rectdim[i])

Bottom-left: (0, 0), Top-right: (0, 0)
[0, 0, 0, 0, 0]
Bottom-left: (0, 0), Top-right: (1, 0)
[0, 0, 1, 0, 0]
Bottom-left: (0, 0), Top-right: (2, 0)
[0, 0, 2, 0, 0]
Bottom-left: (0, 0), Top-right: (3, 0)
[0, 0, 3, 0, 0]
Bottom-left: (0, 0), Top-right: (4, 0)
[0, 0, 4, 0, 0]
Bottom-left: (0, 0), Top-right: (0, 1)
[0, 0, 0, 1, 0]
Bottom-left: (0, 0), Top-right: (1, 1)
[0, 0, 1, 1, 1]
Bottom-left: (0, 0), Top-right: (2, 1)
[0, 0, 2, 1, 2]
Bottom-left: (0, 0), Top-right: (3, 1)
[0, 0, 3, 1, 3]
Bottom-left: (0, 0), Top-right: (4, 1)
[0, 0, 4, 1, 4]
Bottom-left: (0, 0), Top-right: (0, 2)
[0, 0, 0, 2, 0]
Bottom-left: (0, 0), Top-right: (1, 2)
[0, 0, 1, 2, 2]
Bottom-left: (0, 0), Top-right: (2, 2)
[0, 0, 2, 2, 4]
Bottom-left: (0, 0), Top-right: (3, 2)
[0, 0, 3, 2, 6]
Bottom-left: (0, 0), Top-right: (4, 2)
[0, 0, 4, 2, 8]
Bottom-left: (0, 0), Top-right: (0, 3)
[0, 0, 0, 3, 0]
Bottom-left: (0, 0), Top-right: (1, 3)
[0, 0, 1, 3, 3]
Bottom-left: (0, 0), Top-right: (2, 3)
[0, 0, 2, 3, 6]
Bottom-lef

In [12]:
def is_adjacent(rect1, rect2):
    r1,c1,h1,w1=rect1[0],rect1[1],rect1[2],rect1[3]
    r2,c2,h2,w2=rect2[0],rect2[1],rect2[2],rect2[3]
    horiz= (c1 + w1 == c2 or c2 + w2 == c1) and (r1 < r2 + h2 and r2 < r1 + h1)
    vert=(r1 + h1 == r2 or r2 + h2 == r1) and (c1 < c2 + w2 and c2 < c1 + w1)
    return horiz or vert


rectangle1=[0,0,3,2]
rectangle2=[2,2,1,2]
print(is_adjacent(rectangle1, rectangle2))

True


In [ ]:
room=[[1,1,1],[1,1,1]]
grid=[[0,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,0,0],
      [0,0,0,0,1,1,1,1],
      [0,0,0,0,1,1,1,1],
      [0,0,0,0,1,1,1,1],
      [0,0,0,0,1,1,1,1]]
x=3
y=3

for i in range(len(room)):
        for j in range(len(room[0])):
            if x+j>=len(grid[0]) or y+i>=len(grid) or grid[y+i][x+j] != 0:
                print(grid[y+i][x+j], y+i, x+j)
                print("false")
print("true")

1 3 4
false
1 3 5
false
1 4 4
false
1 4 5
false
true
